title: "VapeCorner"
author: "Ken3ie"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
mathjax: true
show_excerpts: false
show_frame: true

navigation:
  - {title: Mail, icon: envelope, url: "mailto:kenziebushell@vapecorner.uk"}
  - {title: Github, icon: github, url: "https://github.com/Ken3ie/"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-feed
